### ISSUE TITLE
USB console support

### ISSUE THREAD

**Issue by BrettVerney** [WLAN-Pi/wlanpi-wconsole#12]
What is required to get this working with network infrastructure that supports USB console? Some switches now only support USB; which effectively installs itself as a USB device to the OS, and emulates a COM port.

I've never attempted to connect to a USB console port on a switch via Linux, so I have no idea re: driver compatibility, but for Windows 10 and 11 most network vendor USB drivers are already installed.

**Comment by jiribrejcha** [comment]
It works out of the box:
https://github.com/WLAN-Pi/wlanpi-wconsole/blob/main/doc/USERGUIDE.md
https://www.jiribrejcha.net/2020/02/wlan-pi-wi-fi-console-multi-port-wireless-terminal-server-for-your-network-devices/

**Comment by BrettVerney** [comment]
I feel so so stupid. Don't know how I missed this. I didn't even attempt to try it either. Thanks for the links!

**Comment by jiribrejcha** [comment]
No problem at all 😉👍🏻
