### ISSUE TITLE
When creating random PSK, don't use difficult to read chars

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/wlanpi-wconsole#8]
Some characters are ambiguous on-screen and may cause users to enter incorrect PSK values. Suggest that at least the following are removed or only capitalized version of the letters are used:

- 1  and l (lower case L) and I (upper case i)
- 0 and O

cc: @jiribrejcha

**Comment by joshschmelzle** [comment]
Fixed in 8f05c89b9b8e6ef2b695a5a6010dce4760aeff72

**Comment by joshschmelzle** [comment]
Released in v1.0.8.
